### ISSUE TITLE
Edit request headers before send it.

### ISSUE THREAD

**Issue by decolector** [runemadsen/HTTP-Requests-for-Processing#10]
I don't know if this is the right place to post this. Here it goes anyway.

Is there any method to add / remove / edit the request headers before sending it ?

Thanks!

**Comment by Avamander** [comment]
I too would like to know.

**Comment by runemadsen** [comment]
There is currently no way of doing this, but it shouldn't be too hard to add. I warmly welcome pull requests, no matter what state they're in :)

**Comment by Avamander** [comment]
@runemadsen I think I would not have this problem if I knew how to do this myself .-.

**Comment by leandro-navarro** [comment]
The addHeader method does that. For instance: 
get.addHeader("Accept", "application/json");
before calling  the send() method.

**Comment by shiffman** [comment]
I believe this is all set now, if not file a new issue. thanks all!

**Comment by PoolloverNathan** [comment]
I think he mentioned editing and removing, not just adding.
