### ISSUE TITLE
HTTP POST returns null pointer exception

### ISSUE THREAD

**Issue by abanks235** [runemadsen/HTTP-Requests-for-Processing#16]
Hi there,

for some reason when I run the post example, the response content is null resulting in a Null Pointer Exception. I've tried it on both Processing 2.2.1 and Processing 3.

HOWEVER, a friend of mine tried it on their computer on Processing 2.2.1 with the same version of Java and it worked. We both have macs. 
Why is it that this library works on some computers and not others? Does it have something to do with my operating system? I have OS X Yosemite 10.10.3

This is the code that I am trying to get to work. It's a very basic HTTP Post that works perfectly with the curl command in terminal. This code worked on my friend's computer as well just like the post example:

import http.requests.*;

public void setup() 
{
	size(400,400);
	smooth();
	PostRequest post = new PostRequest("http://text-processing.com/api/sentiment/");
	post.addData("text", "good");
	post.send();
	System.out.println("Reponse Content: " + post.getContent());
	System.out.println("Reponse Content-Length Header: " + post.getHeader("Content-Length"));
}

**Comment by mjkuwp94** [comment]
I am having the same/similar problem.  I found the code was hanging up on iterating through the header pairs.  In the class PostRequest I added one line as shown below.  Please note that I copied the library into my own sketch in order to do this.  I am quite new at this - I'm sure there is a better way to fix this but I wanted to mention it in case it can help with your debugging.
    
    public PostRequest(String url, String encoding) 
        {
             this.url = url;
             this.encoding = encoding;
             nameValuePairs = new ArrayList<BasicNameValuePair>();
             nameFilePairs = new HashMap<String,File>();
             this.headerPairs = new ArrayList<BasicNameValuePair>(); /* Add this line */
         }

**Comment by janislejins** [comment]
The above fix didn't work for me.

**Comment by acdean** [comment]
https://github.com/runemadsen/HTTP-Requests-for-Processing/pull/17 fixes this but it has yet to be applied.

**Comment by AndrewStyan** [comment]
@acdean I'm fairly ignorant about how github works. How do I implement this fix in my pde code? the changes in #17 appear in my downloaded library src code but I still get the same error as @abanks235 talks about. How does the fix of #17 get "applied" ?

Thanks, Andrew

**Comment by acdean** [comment]
i still don't know how a processing library is made into a library so i just copied the class into a .java file, added that to my project and used the class instead of the library. 

you'll have to ditch the package in the class and the import in the pde code.

**Comment by shiffman** [comment]
This has been fixed with #17.  Updating the release momentarily.
