### ISSUE TITLE
Adding a body to a post request

### ISSUE THREAD

**Issue by criaturaExperimental** [runemadsen/HTTP-Requests-for-Processing#23]
How can I add a body to a post request? Is there a function I could use like write()? Or some type of workaround?

I want to pass this json info as the body of the request:
`{ "url": "http://example.com/picture.jpg" }`

Thanks :)

**Comment by Sega01** [comment]
+1, looking for this feature too.

**Comment by mms92** [comment]
simply use addData( String key, String value ) function from this library , even if i can't use it 'cause processing don't recognize it

**Comment by criaturaExperimental** [comment]
It works, thank you!
