### ISSUE TITLE
installing from the contribution manager

### ISSUE THREAD

**Issue by kasperkamperman** [runemadsen/HTTP-Requests-for-Processing#27]
I try to install the library from the contribution manager in Processing 3.3.6 on OSX. 
I get the announcement: Could not find a library in the downloaded file. 

<img width="752" alt="screen shot 2018-12-12 at 14 20 11" src="https://user-images.githubusercontent.com/1760616/49872359-1719bb80-fe19-11e8-9dc3-70d2180d0881.png">

**Comment by shiffman** [comment]
I think this is a bug in that version of Processing, can you try with 3.4 and see?

**Comment by kasperkamperman** [comment]
Yep, it was a bug in that version of Processing. In 3.4 it works flawless.
