### ISSUE TITLE
Could we make a new release from latest master?

### ISSUE THREAD

**Issue by emilesilvis** [runemadsen/HTTP-Requests-for-Processing#34]
I'd like to use the method for POSTing JSON data.

**Comment by runemadsen** [comment]
I think someone is working on it :)

**Comment by shiffman** [comment]
I tried to build the library. It hasn't been tested. Does this work?

https://github.com/runemadsen/HTTP-Requests-for-Processing/releases/tag/0.1.5.trial

**Comment by emilesilvis** [comment]
I just tested this snippet, and it worked: 

```
import http.requests.*;

public void setup() 
{
  size(400, 400);

  PostRequest post = new PostRequest("http://dummy.restapiexample.com/api/v1/create");
  post.addHeader("Content-type", "application/json;");
  post.addData("{\"name\":\"test\",\"salary\":\"123\",\"age\":\"23\"}");
  post.send();
  System.out.println("Reponse Content: " + post.getContent());
  System.out.println("Reponse Content-Length Header: " + post.getHeader("Content-Length"));
}
```

I can't say if the other changes works. Some unit tests would be awesome :) (hint, hint @tigoe, 
@bnsh)

**Comment by tigoe** [comment]
The examples I added should function pretty well as unit tests, that's what they were intended for.

**Comment by emilesilvis** [comment]
Awesome @tigoe 💪

**Comment by emilesilvis** [comment]
I'm currently updating all examples to work with http://dummy.restapiexample.com, so that the HTTP requests in the examples can be executed against a working service.

**Comment by stephiescastle** [comment]
FWIW I just tested this for `PutRequest` and it works great.

**Comment by shiffman** [comment]
I know it's a year later, but I'm finally made a new release! https://github.com/runemadsen/HTTP-Requests-for-Processing/releases/tag/latest

**Comment by emilesilvis** [comment]
Super!
