### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mitchwagner** [runemadsen/HTTP-Requests-for-Processing#52]
Hi! Thank you for sharing your work. I noticed that on the Processing website, this project was listed as a community-contributed library (https://processing.org/reference/libraries/):

> Contributed libraries are created by members of the Processing community. They are independently and generously created to share. They are all open source and include their own reference and examples.

Of course, there are a wide variety of open-source licenses to choose from, with varying consequences for licensees. I want to be respectful of the project's decision here, but I can't seem to find a license for this library in the repository - would you mind specifying the license under which this code is made available?

**Comment by runemadsen** [comment]
Thanks for pinging me about this. I just added a MIT License to the repo.

**Comment by mitchwagner** [comment]
Thanks for following up!
