### ISSUE TITLE
Basic HTTP auth not working

### ISSUE THREAD

**Issue by runemadsen** [runemadsen/HTTP-Requests-for-Processing#9]
Even though you use a URL like this, it doesn't work:

```
http://user:pass@domain.com
```

**Comment by Brodan** [comment]
I'm going to look into this and add Basic HTTP auth via adding headers/

**Comment by Chuseuiti** [comment]
get.addUser(String, String) does not exist

**Comment by Brodan** [comment]
@Chuseuiti this is probably because the repo is updated but the processing package itself has not been. that is something @runemadsen would have to take care of

**Comment by Chuseuiti** [comment]
From the repo, how can I directly build it to be used in processing?

**Comment by shiffman** [comment]
Hi everyone, thanks for all the recent pull requests and additional functionality!  I'll make a new release of the library right now.  Stay tuned. . .

**Comment by runemadsen** [comment]
@shiffman to the rescue! :boom:

**Comment by Brodan** [comment]
has the package been updated? can this be closed?

**Comment by runemadsen** [comment]
Yup!
